fixtures:
  forge_modules:
    host_core:
      repo: "puppetlabs/host_core"
      puppet_version: '>= 6.0.0'
    mailalias_core:
      repo: "puppetlabs/mailalias_core"
      puppet_version: '>= 6.0.0'
  repositories:
    augeasproviders_core:
      repo: "git://github.com/voxpupuli/augeasproviders_core.git"
  symlinks:
    augeasproviders_base: "#{source_dir}"
